name: build adocs and publish v1 to staging

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: v1

      - name: Build html
        id: adocbuild
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"

      - name: Build pdf
        id: adocbuild_pdf
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -D docs -o files/kvalitet-pa-datasett.pdf -a lang=nb docs/main.adoc"
        continue-on-error: true

      - name: Upload rdf to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.1.0
        id: upload-rdf
        with:
          ontology-type: "specification"
          ontology: "spesifikasjon-for-beskrivelse-av-kvalitet-pa-datasett"
          host: "https://staging.fellesdatakatalog.digdir.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY_STAGING }}
          files: |
            docs/index.html text/html nb
            docs/files/kvalitet_pa_datasett.pdf application/pdf nb files/kvalitet_pa_datasett.pdf
            docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
            docs/images/bilde1_kvalitetsbeskrivelser_dqv.jpg image/jpeg nb images/bilde1_kvalitetsbeskrivelser_dqv.jpg
            docs/images/Eksempler_kvalitetsdimensjoner.png image/png nb images/Eksempler_kvalitetsdimensjoner.png
            docs/images/KlasseneIDQV.png image/png nb images/KlasseneIDQV.png
